### ISSUE TITLE
i tried to textGAN.py but error messege is ..

### ISSUE THREAD

**Issue by DaSol-Park** [dreasysnail/textGAN_public#2]
how to fix error?

Use model cnn_rnn
Use 3 conv/deconv layers
{'restore': True, 'layer': 3, 'fix_emb': False, 'log_path': './log', 'sent_len2': 23, 'n_words': 4391, 'sent_len4': 3, 'filter_size': 300, 'sent_len': 49, 'max_epochs': 100, 'clip_grad': None, 'latent_size': 128, 'maxlen': 41, 'discrimination': False, 'sentence': 40, 'filter_shape': 5, 'decay_rate': 0.99, 'rnn_share_emb': True, 'lr': 1e-05, 'save_path': './save/bird_128_dim_cnn_rnn_s0', 'reuse_w': False, 'attentive_emb': False, 'bp_truncation': None, 'optimizer': 'Adam', 'valid_freq': 100, 'dropout': False, 'sigma_range': [2], 'L': 1000, 'batch_size': 256, 'embed_size': 300, 'dis_steps': 10, 'relu_w': False, 'multiplier': 2, 'cnn_W': None, 'reuse_discrimination': False, 'reuse_cnn': False, 'H_dis': 300, 'n_hid': 100, 'n_gan': 128, 'W_emb': None, 'dropout_ratio': 1, 'tanh': False, 'gen_steps': 1, 'print_freq': 10, 'cnn_b': None, 'substitution': 's', 'stride': [2, 2, 2], 'sent_len3': 10, 'permutation': 0, 'additive_noise_lambda': 0.0, 'model': 'cnn_rnn', 'batch_norm': False}
Total words: 4391
No embedding file found.
[u'pretrain/embed/W:0', u'pretrain/lstm_decoder/weights:0', u'pretrain/lstm_decoder/biases:0', u'pretrain/lstm_decoder/W:0', u'pretrain/lstm_decoder/b:0', u'pretrain/lstm_decoder/embedding_rnn_decoder/rnn_decoder/lstm_cell/kernel:0', u'pretrain/lstm_decoder/embedding_rnn_decoder/rnn_decoder/lstm_cell/bias:0']
Traceback (most recent call last):
  File "textGAN.py", line 432, in <module>
    main()
  File "textGAN.py", line 420, in main
    run_model(opt, train, val, ixtoword)
  File "textGAN.py", line 278, in run_model
    res_, g_loss_, d_loss_, gen_op, dis_op = textGAN(x_, opt)
  File "textGAN.py", line 234, in textGAN
    summaries = summaries
  File "/Desktop/gitProject/textCNN_public-master/textGAN/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 190, in optimize_loss
    (", ".join(OPTIMIZER_SUMMARIES), summ))
ValueError: Summaries should be one of [learning_rate, loss, gradients, gradient_norm], you provided G_loss.

**Comment by XinCynthia** [comment]
same problem, have you solved it?

**Comment by DaSol-Park** [comment]
no,,,i tried to solve the problem, … not solve it still…
